[package]
name = "govarnam"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdb_probe = "0.1.2"
libc = "0.2.139"


[workspace]
members = ["libvarnam-rs"]
